trigger:
  - main

pool:
  name: 'coreone-xpool01EUS' 

variables:
  # Container Registry Variables
  repositoryName: 'stage-go-api'
  # Link to variable group
  # group: 'go-api-variables'

resources:
  repositories:
    - repository: self
      trigger:
        branches:
          include:
            - main

stages:
- stage: Build
  jobs:
  - job: RunTests
    displayName: 'Run Go Tests'
    steps:
    # Setup Go
    - task: GoTool@0
      inputs:
        version: '1.13.5'
      displayName: 'Install Go'
    - task: Go@0
      inputs:
        command: 'test'
        arguments: '-v'
        workingDirectory: '$(System.DefaultWorkingDirectory)'    
        
    # Build and push Docker image
    - task: DockerInstaller@0
      displayName: Docker Installer
      inputs:
        dockerVersion: 17.09.0-ce
        releaseType: stable
    - task: Docker@2
      inputs:
        containerRegistry: 'acrone'
        repository: '$(repositoryName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

# - stage: Deploy
#   dependsOn: Build
#   condition: succeeded()
#   jobs:
#   - deployment: DeployToAzure
#     environment: 'production'
#     pool:
#       vmImage: 'ubuntu-latest'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: AzureWebAppContainer@1
#             inputs:
#               azureSubscription: '$(AZURE_SUBSCRIPTION)'
#               appName: '$(WEBAPP_NAME)'
#               containers: '$(containerRegistry)/$(repositoryName):$(Build.BuildId)'
#               appSettings: |
#                 -WEBSITES_PORT=8087