trigger:
  - main

pool:
  name: 'coreone-xpool01EUS' 

variables:
  repositoryName: 'stage-go-api'
  GOVERSION: '1.21.1'
  webAppName: 'stageone'
  resourceGroup: 'stancorp_appreg_EUS'
  containerRegistry: 'acrone'
  azureServiceConnection: 'appservice' 

resources:
  repositories:
    - repository: self
      trigger:
        branches:
          include:
            - main

stages:
- stage: Build
  jobs:
  - job: RunTests
    displayName: 'Run Go Tests'
    steps:
    # Install build essentials
    # - script: |
    #     sudo apt-get update
    #     sudo apt-get install -y build-essential gcc make
    #   displayName: 'Install Build Essentials'
      
    # Setup Go with specific version
    - task: GoTool@0
      inputs:
        version: '$(GOVERSION)'
      displayName: 'Install Go $(GOVERSION)'
    
    # Download Go dependencies
    - script: |
        go mod download
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Download Dependencies'
    
    # Run tests
    - script: |
        go test -v ./...
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Run Go Tests'
    
    # Verify Docker is available
    - script: |
        docker --version
      displayName: 'Verify Docker Installation'
    
    # Build and push Docker image
    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(repositoryName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployToAzure
    displayName: 'Deploy to Azure Web App'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:

          # First authenticate with Azure
          - task: AzureCLI@2
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Verify authentication
                az account show
                
                # Deploy the container
                az webapp config container set \
                  --name $(webAppName) \
                  --resource-group $(resourceGroup) \
                  --docker-custom-image-name $(containerRegistry)/$(repositoryName):$(Build.BuildId) \
                  --docker-registry-server-url https://$(containerRegistry)

          - task: AzureWebAppContainer@1
            displayName: 'Deploy Container to Azure Web App'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              resourceGroupName: '$(resourceGroup)'
              appName: '$(WEBAPP_NAME)'
              containers: '$(containerRegistry)/$(repositoryName):$(Build.BuildId)'
              appSettings: |
                -WEBSITES_PORT=8087
                -WEBSITES_ENABLE_APP_SERVICE_STORAGE=false

          - script: |
              sleep 30
              echo "Checking deployment status..."
              curl -s -o /dev/null -w "%{http_code}" https://$(webAppName).azurewebsites.net/
            displayName: 'Verify Deployment'
            # continueOnError: true
