trigger:
  - main

pool:
  name: 'coreone-xpool01EUS' 

variables:
  repositoryName: 'stage-go-api'
  GOVERSION: '1.21.1'
  webAppName: 'stageone'
  containerRegistry: 'acrone'

resources:
  repositories:
    - repository: self
      trigger:
        branches:
          include:
            - main

stages:
- stage: Build
  jobs:
  - job: RunTests
    displayName: 'Run Go Tests'
    steps:
     
    # Setup Go with specific version
    - task: GoTool@0
      inputs:
        version: '$(GOVERSION)'
      displayName: 'Install Go $(GOVERSION)'
    
    # Download Go dependencies
    - script: |
        go mod download
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Download Dependencies'
    
    # Run tests
    - script: |
        go test -v ./...
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Run Go Tests'
    
    # Verify Docker is available
    - script: |
        docker --version
      displayName: 'Verify Docker Installation'
    
    # Build and push Docker image
    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(repositoryName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)'
        tags: |
          $(Build.BuildId)
          latest